In [38]:
import pandas as pd
import numpy as np
import seaborn as sns

In [39]:
df = pd.read_csv('/kaggle/input/tipping/tips.csv')

In [40]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [41]:
# NORMAL GROUPBY

In [42]:
df.groupby('time')['total_bill'].mean()

time
Dinner    20.797159
Lunch     17.168676
Name: total_bill, dtype: float64

In [43]:
# TO_FRAME

In [44]:
df.groupby('time')['total_bill'].mean().to_frame('avg_bill')

         avg_bill
time
Dinner  20.797159
Lunch   17.168676

In [45]:
df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending = False)

     time   avg_bill
0  Dinner  20.797159
1   Lunch  17.168676

In [46]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [47]:
df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending = False)

     time   avg_bill
0  Dinner  20.797159
1   Lunch  17.168676

In [48]:
# ASSIGN IT TO NEW DATAFRAME

In [49]:
avgbill = df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending = False)

In [50]:
avgbill.head()

     time   avg_bill
0  Dinner  20.797159
1   Lunch  17.168676

In [51]:
# COMMON CALCULATIONS

In [52]:
df.groupby('time')['total_bill'].count()

time
Dinner    176
Lunch      68
Name: total_bill, dtype: int64

In [53]:
df.groupby('time')['total_bill'].nunique()

time
Dinner    168
Lunch      64
Name: total_bill, dtype: int64

In [54]:
df.groupby('time')['total_bill'].size()

time
Dinner    176
Lunch      68
Name: total_bill, dtype: int64

In [55]:

df.groupby('time')['total_bill'].max()

time
Dinner    50.81
Lunch     43.11
Name: total_bill, dtype: float64

In [56]:
df.groupby('time')['total_bill'].min()

time
Dinner    3.07
Lunch     7.51
Name: total_bill, dtype: float64

In [57]:
df.groupby('time')['total_bill'].sum().reset_index()

     time  total_bill
0  Dinner     3660.30
1   Lunch     1167.47

In [58]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [59]:
df.groupby(['time','sex'])['total_bill'].mean().reset_index()

     time     sex  total_bill
0  Dinner  Female   19.213077
1  Dinner    Male   21.461452
2   Lunch  Female   16.339143
3   Lunch    Male   18.048485

In [60]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [61]:
# CALCULATE THE AVERAGE TIP FOR EACH NIGHT OF THE WEEK

In [62]:
df.groupby('day')['tip'].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [63]:
# MAX TIP FOR EACH SEX

In [64]:
df.groupby('sex')['tip'].max()

sex
Female     6.5
Male      10.0
Name: tip, dtype: float64

In [65]:
# CALCULATE THE TOP 10% OF  TIPS EACH NIGHT

In [66]:
df.groupby('day')['tip'].quantile(.9)

day
Fri     4.060
Sat     4.802
Sun     5.035
Thur    4.920
Name: tip, dtype: float64

In [67]:
# MULTIPLE CALCULATIONS .AGG() + FORMATS

In [68]:
df.groupby('time')['total_bill'].agg(minimum = 'min', median = np.median, maximum = 'max').reset_index()

     time  minimum  median  maximum
0  Dinner     3.07  18.390    50.81
1   Lunch     7.51  15.965    43.11

In [69]:
df.groupby('time')['total_bill'].describe()

        count       mean       std   min      25%     50%      75%    max
time
Dinner  176.0  20.797159  9.142029  3.07  14.4375  18.390  25.2825  50.81
Lunch    68.0  17.168676  7.713882  7.51  12.2350  15.965  19.5325  43.11

In [70]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [71]:
# CALCULATING MULTIPLE COLUMNS

In [72]:
df.groupby(['day','time'])[['tip','total_bill']].mean().reset_index()

    day    time       tip  total_bill
0   Fri  Dinner  2.940000   19.663333
1   Fri   Lunch  2.382857   12.845714
2   Sat  Dinner  2.993103   20.441379
3   Sun  Dinner  3.255132   21.410000
4  Thur  Dinner  3.000000   18.780000
5  Thur   Lunch  2.767705   17.664754

In [73]:
# TRANSFORM

In [74]:
dftransform

NameError: name 'dftransform' is not defined

In [ ]:
dftransform = pd.read_csv('/kaggle/input/tipping/tips.csv')

In [ ]:
dftransform['medianbill']= df.groupby('time')['total_bill'].transform('median')

In [ ]:
dftransform['medianbill']